sky:
  redis:
    host: localhost
    port: 6379
    password: 20030503_Zrd
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20030503_Zrd