sky:
  redis:
    host: localhost
    port: 6379
    password: 20030503_Zrd
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20030503_Zrd
  wechat:
    appid: wxe5c17d39ac67d23b
    secret: 467ad623342de7262e58f51a94a94bed